### ISSUE TITLE
Max distance ?

### ISSUE THREAD

**Issue by aamirshah** [borismus/sonicnet.js#10]
First of all Excellent implementation.

I wanted to know is it possible to tweak the code so that it works for a distance of around ~3 feet. As of now it works only when I hold the mobile and the laptop next to each.

**Comment by oslego** [comment]
The quality of the speakers and microphone on the devices influences the range / accuracy. Phones have generally mediocre speakers and microphones optimized for speech, therefore you'll get less range or none at all. 

You'll get better range when using sounds in the audible spectrum, even with lower quality hardware.

**Comment by borismus** [comment]
Determining distance with audio is an ongoing research problem and out of scope for this project.
