### ISSUE TITLE
Won't work on mobile safari

### ISSUE THREAD

**Issue by oscarqht** [borismus/sonicnet.js#20]
When visiting the [send-emotion](http://borismus.github.io/sonicnet.js/emoticons/) demo on Mobile Safari. I get the following error:

```
TypeError: navigator.webkitGetUserMedia is not a function.
```

A search on [caniuse](http://caniuse.com/#search=webrtc) shows that neither Safari nor Mobile Safari support WebRTC so far. Is there an alternative to WebRTC to read audio input?

**Comment by borismus** [comment]
Unfortunately no.
