### ISSUE TITLE
lib/api-test.html error

### ISSUE THREAD

**Issue by ghost** [borismus/sonicnet.js#23]
api-test.html:18 Uncaught ReferenceError: SonicServer is not defined

**Comment by Astriel** [comment]
There is actually a pull request which can solve that problem, you can find it here : https://github.com/borismus/sonicnet.js/pull/18. 

Did you manage to make it work ? I'm actually having some trouble to test it.

**Comment by Astriel** [comment]
Did you manage to make other part of the library working ? I'm still strugling with it.
